{% set name = "File-Path" %}
{% set version = "2.18" %}

package:
  name: perl-{{ name|lower }}
  version: {{ version }}

source:
  - url: https://cpan.metacpan.org/authors/id/J/JK/JKEENAN/{{ name }}-{{ version }}.tar.gz
    sha256: 980f0a17edb353df46e9cd7b357f9f5929cde0f80c45fd7a06cf7e0e8bd6addd
  - url: https://raw.githubusercontent.com/Perl/perl5/v5.32.1/Copying
    sha256: d77d235e41d54594865151f4751e835c5a82322b0e87ace266567c3391a4b912
  - url: https://raw.githubusercontent.com/Perl/perl5/v5.32.1/Artistic
    sha256: dd90d4f42e4dcadf5a7c09eea0189d93c7b37ae560c91f0f6d5233ed3b9292a2

build:
  number: 0
  noarch: generic
  script:
    - perl Makefile.PL INSTALLDIRS=vendor NO_PERLLOCAL=1 NO_PACKLIST=1
    - make
    - make test
    - make install VERBINST=1

requirements:
  build:
    - make
  host:
    - perl
    - perl-carp
    - perl-exporter
    - perl-extutils-makemaker

  run:
    - perl
    - perl-exporter

test:
  imports:
    - File::Path

about:
  home: https://metacpan.org/release/{{ name }}
  license: GPL-1.0-or-later OR Artistic-1.0-Perl
  license_family: OTHER
  license_file:
    - Artistic
    - Copying
  summary: Create or remove directory trees

extra:
  recipe-maintainers:
    - tdegeus
